name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get Git tag name
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      shell: bash
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Pack project
      run: dotnet pack Russlyman.Rcon -c Release -o pack -p:Version=${{ steps.get_version.outputs.VERSION }}
    - name: Push to NuGet
      run: dotnet nuget push pack/Russlyman.Rcon.${{ steps.get_version.outputs.VERSION }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
    - name: Create archive
      run: zip -j Russlyman.Rcon-${{ steps.get_version.outputs.VERSION }}.zip Russlyman.Rcon/bin/Release/net6.0/Russlyman.Rcon.dll Russlyman.Rcon/bin/Release/net6.0/Russlyman.Rcon.pdb LICENSE
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: Russlyman.Rcon-${{ steps.get_version.outputs.VERSION }}.zip